### ISSUE TITLE
ReactDOMServer 0.14.0 doesn't eval on Java 8 Nashorn JavaScript Engine

### ISSUE THREAD

**Issue by aantono** [webjars/react#20]
Any way to handle https://github.com/facebook/react/issues/5311 during webjar creation?

**Comment by jamesward** [comment]
It sounds like you just need to load a global from a different WebJar.  But I don't fully understand the problem.

**Comment by aantono** [comment]
What webjar would you suggest?
Based on the discussion in the fb issue (linked to here) it seems like the problem is that during the creation of the js files (browserify or what else is being used) the ReactDOMServer reference is not exported (unlike ReactDOM does)
Can that be fixed during the preparation of the js files?

**Comment by Download** [comment]
Yes, the problem is that only `React` and `ReactDOM` objects are exposed to global, but not `ReactDOMServer`. So if tou don't have access to `require` (all systems but Node basically), there is no way (any more) to use `renderToString` since it has moved from `React` to `ReactDOMServer`.

I get that you want to minimize the API footprint/surface area. We don't want a whole bunch of objects in global. But what about a middle ground where we expose `ReactDOMServer` via one of the objects that are already in global?

E.g. I'd love to be able to do this:

```js
var ReactDOMServer = ReactDOM.ReactDOMServer;
```

It would be a single line of code in the React codebase and would make it *much* simpler to use React on e.g. Nashorn. As it stands we are forced to either polyfill the CommonJS module system or use Node+Broswerify+Babel / Node+Webpack+Babel etc combinations to build a bundle file that does expose `ReactDOMServer`.

**Comment by jamesward** [comment]
> Can that be fixed during the preparation of the js files?

There isn't any preparation for this WebJar.  The upstream zip is downloaded and then repackaged into a WebJar.

I'm not sure if there is anything that can be done in the WebJar.  But I'll leave this open since I don't fully understand the issue.

**Comment by Download** [comment]
It is my understanding that [this pull request](https://github.com/facebook/react/pull/5381) will fix this issue. So I think this one can be closed.
